"use client"
import { useState } from "react"
import Image from "next/image"
import { X } from "lucide-react"

type Inverter = {
  name: string
  summary: string
  description: string
  features: string[]
  applications: string[]
  image: string
}

const inverters: Inverter[] = [
  {
    name: "POLYCAB Inverter",
    summary: "High-efficiency grid-tie string inverters engineered for Indian conditions.",
    description:
      "Polycab solar inverters are reliable grid-tie string inverters designed to convert DC power generated by solar panels into AC electricity for homes, businesses, and industries. Built for Indian solar applications, they offer high efficiency, durability, and smart monitoring options.",
    features: [
      "High Efficiency & Power Conversion: Maximizes usable AC energy from solar DC input",
      "Advanced MPPT Technology: Extracts maximum power from panels throughout the day",
      "Wide Capacity Range: Single-phase options for homes and three-phase for C&I projects",
      "Premium Protection: IP65 enclosure with surge, over/under-voltage, and anti-islanding safety",
      "Remote Monitoring: Wi‑Fi / GPRS / LAN options for app and web-based monitoring",
      "Strong Warranty & Support: Standard long-term warranty with extension options",
    ],
    applications: [
      "Residential rooftop on‑grid systems with net metering",
      "Commercial and industrial solar plants with higher capacities",
      "Projects requiring robust protection and remote performance tracking",
    ],
    image: "/Polycab Solar invertor.webp",
  },
  {
    name: "UTL Inverter",
    summary: "Versatile on-grid, off-grid, and hybrid inverters for every solar setup.",
    description:
      "UTL solar inverters convert DC power from solar panels into AC electricity for homes, offices, and industries. UTL offers a wide range of on-grid, off-grid, and hybrid inverters suitable for residential, commercial, and industrial solar installations.",
    features: [
      "High Efficiency MPPT: Maximizes power extraction from solar panels",
      "On‑Grid & Off‑Grid Options: Supports grid-tie and standalone systems with batteries",
      "Rugged Design: IP65-rated outdoor models with multiple electrical protections",
      "Remote Monitoring: Wi‑Fi / LAN connectivity for real-time tracking",
      "Wide Power Range: From small single-phase to large three-phase inverters",
    ],
    applications: [
      "Residential rooftops with net metering",
      "Commercial and industrial solar systems",
      "Off‑grid and backup systems in remote or power-deficit areas",
      "Battery-based systems like UTL Gamma Plus and Sun Plus Pro series",
    ],
    image: "/UTL solar Invertor.webp",
  },
  {
    name: "WAAREE Inverter",
    summary: "High-performance inverters from one of India’s leading solar brands.",
    description:
      "Waaree solar inverters convert DC electricity from panels into AC power for homes, businesses, and industries. With high efficiency, robust construction, and smart connectivity, they help maximize energy yield from your solar installation.",
    features: [
      "Efficient Power Conversion: Up to ~98%+ efficiency for higher output",
      "MPPT Technology: Ensures maximum available power is harvested from the array",
      "Smart Monitoring & Connectivity: Wi‑Fi, RS485, and GPRS options for remote viewing",
      "IP65 Weather Protection: Dust- and water-resistant housing for long service life",
      "User-Friendly Interface: Intuitive displays and simple installation",
    ],
    applications: [
      "On-grid residential and small commercial rooftop systems",
      "Off‑grid / hybrid systems with battery backup where required",
      "C&I rooftop plants from a few kW to tens of kW capacity",
    ],
    image: "/Waaree Solar Invertor.webp",
  },
  {
    name: "STATCON Inverter",
    summary: "Hybrid and off‑grid inverters with flexible operating modes.",
    description:
      "Statcon solar inverters from Statcon Energiaa are high-performance power converters available in off‑grid, hybrid, and on‑grid variants. They are designed to handle DC from solar panels, manage batteries, and supply AC power reliably in homes, businesses, and industrial sites.",
    features: [
      "MPPT Technology: Maximizes solar energy extraction from PV arrays",
      "Multiple Operating Modes: Solar‑first, grid‑assist, battery‑backup and more",
      "Hybrid & Off‑Grid Support: Works seamlessly with solar panels and batteries",
      "Robust Build: Engineered for Indian climate with strong electrical protections",
      "Smart Monitoring: Digital displays and optional data logging / remote monitoring",
    ],
    applications: [
      "Residential rooftops needing backup during grid outages",
      "Commercial and industrial hybrid systems with high load demands",
      "Dedicated backup power systems combining solar, grid, and batteries",
    ],
    image: "/Statecon Solar Invertor.webp",
  },
]

export function InverterDescriptionSection() {
  const [active, setActive] = useState<Inverter | null>(null)

  return (
    <section className="bg-white py-12 md:py-20 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-6">
          <div className="inline-block bg-[#E9F6FF] px-6 py-2 rounded-full mb-4">
            <span className="text-[#0A6FB0] font-semibold text-sm md:text-base">High-Performance Solar Inverters</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-bold text-gray-800 mb-3">Inverters</h2>
          <p className="text-gray-600 text-sm md:text-base">
            Reliable Indian and global brands for residential, commercial, and industrial solar power conversion.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {inverters.map((inv) => (
            <div
              key={inv.name}
              className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition flex flex-col"
            >
              <div className="relative w-full h-40 mb-4 rounded-lg overflow-hidden bg-gray-100">
                <Image src={inv.image} alt={inv.name} fill className="object-contain" />
              </div>
              <div className="mb-3">
                <h3 className="text-lg font-semibold text-gray-800 leading-snug">{inv.name}</h3>
                <p className="text-gray-600 text-sm leading-relaxed mt-1 line-clamp-3">{inv.summary}</p>
              </div>
              <div className="mt-auto">
                <button
                  onClick={() => setActive(inv)}
                  className="mt-4 inline-flex items-center justify-center px-4 py-2 bg-[#0A6FB0] text-white text-sm font-semibold rounded-md hover:bg-[#083B63] transition w-full"
                >
                  View Details
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {active && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center px-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-5xl w-full max-h-[90vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
              <div>
                <h3 className="text-xl font-bold text-gray-800">{active.name}</h3>
                <p className="text-gray-600 text-sm mt-1">{active.summary}</p>
              </div>
              <button
                aria-label="Close"
                onClick={() => setActive(null)}
                className="p-2 rounded-full hover:bg-gray-100 text-gray-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="flex-1 overflow-hidden">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-0 h-full">
                {/* Left Side - Description */}
                <div className="p-5 md:p-6 space-y-4 overflow-y-auto">
                  {/* Mobile Image */}
                  <div className="md:hidden relative w-full h-40 mb-4 rounded-lg overflow-hidden bg-gray-100">
                    <Image src={active.image} alt={active.name} fill className="object-contain" />
                  </div>
                  <p className="text-gray-700 text-base leading-relaxed">{active.description}</p>

                  <div>
                    <h4 className="text-lg font-semibold text-gray-800 mb-2">Key Features &amp; Benefits</h4>
                    <ul className="list-disc list-inside text-gray-700 text-sm md:text-base space-y-2">
                      {active.features.map((feature) => (
                        <li key={feature}>{feature}</li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="text-lg font-semibold text-gray-800 mb-2">Applications</h4>
                    <ul className="list-disc list-inside text-gray-700 text-sm md:text-base space-y-2">
                      {active.applications.map((app) => (
                        <li key={app}>{app}</li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Right Side - Image */}
                <div className="hidden md:flex items-center justify-center p-5 md:p-6 bg-gray-50">
                  <div className="relative w-full h-full min-h-[320px] rounded-lg overflow-hidden">
                    <Image src={active.image} alt={active.name} fill className="object-contain" />
                  </div>
                </div>
              </div>
            </div>
            <div className="px-5 py-4 border-t border-gray-200 flex justify-end">
              <button
                onClick={() => setActive(null)}
                className="px-4 py-2 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 text-sm font-semibold"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}


